version: 2

jobs:
  build_push:
    docker:
      - image: docker:18.02
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install packages
          command: apk --no-cache add bash curl pcre-tools
      - run:
          name: Build docker images
          command: |
            ./build.sh
      - run:
          name: Run tests
          command: |
            ./test.sh
      - run:
          name: Push docker images
          shell: /bin/bash -Eeuo pipefail
          command: |
            does_repo_exist() {
              curl --silent -f -lSL https://index.docker.io/v1/repositories/scalableminds/$1/tags > /dev/null
            }

            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            for APP in $(./get_valid_order.sh); do
              echo ""
              echo "####### ${APP} #######"
              echo ""
              if does_repo_exist $APP; then
                docker push scalableminds/$APP:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
                docker push scalableminds/$APP:${CIRCLE_BRANCH}
                eval "MICROBADGER_HOOK=\$MICROBADGER_HOOK_$APP"
                curl --silent -f -lSL -X POST $MICROBADGER_HOOK
              else
                docker tag \
                  scalableminds/$APP:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
                  scalableminds/various:${APP}__${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
                docker push scalableminds/various:${APP}__${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
                docker tag \
                  scalableminds/$APP:${CIRCLE_BRANCH} \
                  scalableminds/various:${APP}__${CIRCLE_BRANCH}
                docker push scalableminds/various:${APP}__${CIRCLE_BRANCH}
              fi
            done
            curl --silent -f -lSL -X POST $MICROBADGER_HOOK_various
            docker logout

workflows:
  version: 2
  default:
    jobs:
      - build_push
