version: 2

jobs:
  build_push:
    docker:
      - image: docker:18.02
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker images
          command: |
            for APP in */; do
              APP="${APP%/}"
              cd $APP
              docker build \
                -t scalableminds/$APP:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
                -t scalableminds/$APP:${CIRCLE_BRANCH} \
                .
              cd ..
            done
      - run:
          name: Push docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            for APP in */; do
              APP="${APP%/}"
              docker push scalableminds/$APP:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
              docker push scalableminds/$APP:${CIRCLE_BRANCH}
            done
            docker logout

workflows:
  version: 2
  default:
    jobs:
      - build_push
