server:
  disable: true
clients:
- url: ${LOKI_PUSH_URL}
  basic_auth:
    username: ${LOKI_PUSH_USER}
    password: ${LOKI_PUSH_PASSWORD}
scrape_configs:
- job_name: docker
  docker_sd_configs:
  - host: ${DOCKER_HOST}
  relabel_configs:
  - source_labels: ['__meta_docker_container_name']
    regex: '/(.*)'
    target_label: 'container'
  - source_labels: ['__meta_docker_container_label_gather_logs']
    regex: 'true'
    action: 'keep'
  - source_labels: ['__meta_docker_container_label_gather_logs']
    regex: '.*'
    target_label: 'instance'
    replacement: ${INSTANCE_NAME}
