name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker images
      run: |
        CI_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        NORMALIZED_CI_BRANCH=${CI_BRANCH//[\/-]/_}
        ./build.sh
    - name: Run tests
      run: ./test.sh
    - name: Push docker images
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        CI_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        NORMALIZED_CI_BRANCH=${CI_BRANCH//[\/-]/_}
        does_repo_exist() {
          curl --silent -f -lSL https://index.docker.io/v1/repositories/scalableminds/$1/tags > /dev/null
        }

        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        for APP in $(./get_valid_order.sh); do
          echo ""
          echo "####### ${APP} #######"
          echo ""
          if does_repo_exist $APP; then
            docker push scalableminds/$APP:${NORMALIZED_CI_BRANCH}__${GITHUB_RUN_ID}
            docker push scalableminds/$APP:${NORMALIZED_CI_BRANCH}
            # eval "MICROBADGER_HOOK=\$MICROBADGER_HOOK_${APP/-/}"
            curl --silent -f -lSL -X POST $MICROBADGER_HOOK
          else
            docker tag \
              scalableminds/$APP:${NORMALIZED_CI_BRANCH}__${GITHUB_RUN_ID} \
              scalableminds/various:${APP}__${NORMALIZED_CI_BRANCH}__${GITHUB_RUN_ID}
            docker push scalableminds/various:${APP}__${NORMALIZED_CI_BRANCH}__${GITHUB_RUN_ID}
            docker tag \
              scalableminds/$APP:${NORMALIZED_CI_BRANCH} \
              scalableminds/various:${APP}__${NORMALIZED_CI_BRANCH}
            docker push scalableminds/various:${APP}__${NORMALIZED_CI_BRANCH}
          fi
        done
        # curl --silent -f -lSL -X POST $MICROBADGER_HOOK_various
        docker logout
